# Generated by Django 3.2.10 on 2021-12-21 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sexe', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NewRecrue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='')),
                ('cv', models.FileField(upload_to='')),
                ('message', models.TextField()),
                ('idcard', models.FileField(upload_to='')),
                ('diplome', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deactivated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('usersN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation', to='recrues.usersn')),
            ],
        ),
    ]
