# Generated by Django 3.2.10 on 2021-12-29 18:55

from django.db import migrations, models
import recrues.models


class Migration(migrations.Migration):

    dependencies = [
        ('recrues', '0002_auto_20211228_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newrecrue',
            name='cv',
            field=models.FileField(blank=True, upload_to=recrues.models.uploadFile),
        ),
        migrations.AlterField(
            model_name='newrecrue',
            name='idcard',
            field=models.FileField(upload_to=recrues.models.uploadFile),
        ),
        migrations.AlterField(
            model_name='newrecrue',
            name='picture',
            field=models.FileField(blank=True, upload_to=recrues.models.uploadFile),
        ),
    ]
