# Generated by Django 3.2.10 on 2021-12-30 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recrues', '0004_auto_20211229_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRecrueRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='image')),
                ('diplome', models.CharField(choices=[('partiel', 'Temps partiel'), ('Plein', 'Temps plein')], max_length=50)),
                ('message', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
