# Generated by Django 3.2.10 on 2021-12-31 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recrues', '0006_newrecrueregister2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrecrueregister2',
            name='diplome',
            field=models.CharField(choices=[('partiel', 'Temps Partiel'), ('Plein', 'Temps Plein')], max_length=50),
        ),
        migrations.CreateModel(
            name='NewRecrueRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='Telecharger votre image')),
                ('cv', models.FileField(upload_to='', verbose_name='Telecharger votre CV')),
                ('mode', models.CharField(choices=[('temps partiel', 'Temps Partiel'), ('temps Plein', 'Temps Plein')], max_length=50)),
                ('message', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
