# Generated by Django 3.2.10 on 2022-01-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrues', '0007_auto_20211231_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrecrueregistration',
            name='register_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newrecrueregistration',
            name='telephone',
            field=models.IntegerField(default=1245),
            preserve_default=False,
        ),
    ]
